name: ranker
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch
  # - pytorch-cuda=12.1
  - pandas
  - pip
  - pip:
      - --extra-index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-12/pypi/simple/
      - optimum[onnxruntime-gpu]
      - fastapi==0.111.0
      - fasttext_wheel==0.9.2
      - huggingface_hub==0.23.3
      - lexicalrichness==0.5.1
      - numpy==1.26.4
      - pandas==2.2.2
      - pydantic==2.7.4
      - ranking_challenge==2.0.0
      - sentence_transformers==3.0.1
      - transformers==4.41.2
      - uvicorn==0.30.1
      - simplejson
      - numexpr
      - bottleneck
